const USER_DATA_BOX_KEY = 'USER_DATA_BOX';
const USER_DETAIL_KEY = 'USER_DETAIL';
const USER_LOGGED_IN_KEY = 'USER_LOGGED_IN';

const USER_TOTAL_SMALL_MOSQUE_KEY = 'USER_TOTAL_SMALL_MOSQUE';
const USER_TOTAL_MEDIUM_MOSQUE_KEY = 'USER_TOTAL_MEDIUM_MOSQUE';
const USER_TOTAL_LARGE_MOSQUE_KEY = 'USER_TOTAL_LARGE_MOSQUE';
const USER_TOTAL_MOSQUE_KEY = 'USER_TOTAL_MOSQUE';
const USER_MOSQUES_KEY = 'USER_MOSQUES';


// 
const DASHBOARD_TITLE = 'Dashboard';
const PROFILE_TITLE = 'Profile';
const ALL_MOSQUE_TITLE = 'All Mosques';